import type { MathSkillId, SkillState } from "./types";

export type MathSection =
  | "addition"
  | "subtraction"
  | "compare"
  | "missing"
  | "word"
  | "series"
  | "length"
  | "geometry"
  | "multiplication"
  | "division";

export type CurriculumSkill = {
  skillId: MathSkillId;
  section: MathSection;
  title: string;
  shortTitle: string;
  description: string;
  prerequisites: MathSkillId[];
  defaultState: SkillState;
  order: number;
};

/** Каталог математической программы 2 класса (данные, без UI). */
export const MATH_CURRICULUM: CurriculumSkill[] = [
  // Сложение
  {
    skillId: "add_to_10",
    section: "addition",
    title: "Сложение до 10",
    shortTitle: "До 10",
    description: "Сложить два числа, сумма не больше 10",
    prerequisites: [],
    defaultState: "learning",
    order: 10,
  },
  {
    skillId: "add_to_20_no_bridge",
    section: "addition",
    title: "Сложение до 20 без перехода",
    shortTitle: "До 20",
    description: "Сумма до 20, без перехода через десяток",
    prerequisites: ["add_to_10"],
    defaultState: "learning",
    order: 20,
  },
  {
    skillId: "add_to_20_bridge",
    section: "addition",
    title: "Сложение через десяток",
    shortTitle: "Через 10",
    description: "Сложение с переходом через десяток (до 10)",
    prerequisites: ["add_to_20_no_bridge"],
    defaultState: "learning",
    order: 30,
  },
  {
    skillId: "add_tens",
    section: "addition",
    title: "Сложение круглых десятков",
    shortTitle: "Десятки",
    description: "Сложить круглые десятки",
    prerequisites: ["add_to_10"],
    defaultState: "learning",
    order: 40,
  },
  {
    skillId: "add_2digit_1digit",
    section: "addition",
    title: "Двузначное + однозначное",
    shortTitle: "2+1",
    description: "Прибавить однозначное к двузначному",
    prerequisites: ["add_to_20_bridge"],
    defaultState: "practice",
    order: 50,
  },
  {
    skillId: "add_2digit_2digit",
    section: "addition",
    title: "Двузначное + двузначное",
    shortTitle: "2+2",
    description: "Сложить два двузначных числа",
    prerequisites: ["add_2digit_1digit"],
    defaultState: "practice",
    order: 60,
  },
  // Вычитание
  {
    skillId: "sub_to_10",
    section: "subtraction",
    title: "Вычитание до 10",
    shortTitle: "До 10",
    description: "Вычесть в пределах 10",
    prerequisites: [],
    defaultState: "learning",
    order: 110,
  },
  {
    skillId: "sub_to_20_no_bridge",
    section: "subtraction",
    title: "Вычитание до 20 без перехода",
    shortTitle: "До 20",
    description: "Вычитание без перехода через десяток",
    prerequisites: ["sub_to_10"],
    defaultState: "learning",
    order: 120,
  },
  {
    skillId: "sub_to_20_bridge",
    section: "subtraction",
    title: "Вычитание через десяток",
    shortTitle: "Через 10",
    description: "Вычитание с переходом (через 10)",
    prerequisites: ["sub_to_20_no_bridge"],
    defaultState: "learning",
    order: 130,
  },
  {
    skillId: "sub_tens",
    section: "subtraction",
    title: "Вычитание круглых десятков",
    shortTitle: "Десятки",
    description: "Вычесть круглые десятки",
    prerequisites: ["sub_to_10"],
    defaultState: "learning",
    order: 140,
  },
  {
    skillId: "sub_2digit_1digit",
    section: "subtraction",
    title: "Двузначное − однозначное",
    shortTitle: "2−1",
    description: "Вычесть однозначное из двузначного",
    prerequisites: ["sub_to_20_bridge"],
    defaultState: "practice",
    order: 150,
  },
  {
    skillId: "sub_2digit_2digit",
    section: "subtraction",
    title: "Двузначное − двузначное",
    shortTitle: "2−2",
    description: "Вычесть двузначное из двузначного",
    prerequisites: ["sub_2digit_1digit"],
    defaultState: "practice",
    order: 160,
  },
  // Сравнение
  {
    skillId: "compare_numbers",
    section: "compare",
    title: "Сравнить числа",
    shortTitle: "Числа",
    description: "Сравнить два числа знаками < = >",
    prerequisites: [],
    defaultState: "learning",
    order: 210,
  },
  {
    skillId: "compare_expression_number",
    section: "compare",
    title: "Сравнить выражение и число",
    shortTitle: "Сумма ○ число",
    description: "Сложить и сравнить с числом",
    prerequisites: ["compare_numbers", "add_to_20_no_bridge"],
    defaultState: "learning",
    order: 220,
  },
  {
    skillId: "compare_expressions",
    section: "compare",
    title: "Сравнить два выражения",
    shortTitle: "Два выражения",
    description: "Сравнить результаты двух выражений",
    prerequisites: ["compare_expression_number"],
    defaultState: "practice",
    order: 230,
  },
  // Неизвестное
  {
    skillId: "missing_addend",
    section: "missing",
    title: "Найди слагаемое",
    shortTitle: "□ +",
    description: "Найти неизвестное слагаемое",
    prerequisites: ["add_to_20_no_bridge"],
    defaultState: "learning",
    order: 310,
  },
  {
    skillId: "missing_minuend",
    section: "missing",
    title: "Найди уменьшаемое",
    shortTitle: "□ −",
    description: "Найти неизвестное уменьшаемое",
    prerequisites: ["sub_to_20_no_bridge"],
    defaultState: "learning",
    order: 320,
  },
  {
    skillId: "missing_subtrahend",
    section: "missing",
    title: "Найди вычитаемое",
    shortTitle: "− □",
    description: "Найти неизвестное вычитаемое",
    prerequisites: ["sub_to_20_no_bridge"],
    defaultState: "learning",
    order: 330,
  },
  // Задачи
  {
    skillId: "word_add",
    section: "word",
    title: "Задача на сложение",
    shortTitle: "Сложение",
    description: "Простая текстовая задача на сложение",
    prerequisites: ["add_to_20_no_bridge"],
    defaultState: "learning",
    order: 410,
  },
  {
    skillId: "word_sub",
    section: "word",
    title: "Задача на вычитание",
    shortTitle: "Вычитание",
    description: "Простая текстовая задача на вычитание",
    prerequisites: ["sub_to_20_no_bridge"],
    defaultState: "learning",
    order: 420,
  },
  {
    skillId: "word_compare_more",
    section: "word",
    title: "На сколько больше",
    shortTitle: "Больше",
    description: "Задача «на сколько больше»",
    prerequisites: ["word_sub"],
    defaultState: "practice",
    order: 430,
  },
  {
    skillId: "word_compare_less",
    section: "word",
    title: "На сколько меньше",
    shortTitle: "Меньше",
    description: "Задача «на сколько меньше»",
    prerequisites: ["word_sub"],
    defaultState: "practice",
    order: 440,
  },
  {
    skillId: "word_two_step",
    section: "word",
    title: "Задача в два действия",
    shortTitle: "Два шага",
    description: "Текстовая задача в два действия",
    prerequisites: ["word_add", "word_sub"],
    defaultState: "practice",
    order: 450,
  },
  {
    skillId: "word_money",
    section: "word",
    title: "Задачи про деньги",
    shortTitle: "Деньги",
    description: "Задачи с рублями",
    prerequisites: ["word_add", "word_sub"],
    defaultState: "practice",
    order: 460,
  },
  {
    skillId: "word_length",
    section: "word",
    title: "Задачи про длину",
    shortTitle: "Длина",
    description: "Задачи с сантиметрами",
    prerequisites: ["word_add", "word_sub"],
    defaultState: "practice",
    order: 470,
  },
  // Ряды
  {
    skillId: "series_add",
    section: "series",
    title: "Возрастающий ряд",
    shortTitle: "+шаг",
    description: "Продолжить ряд с прибавлением",
    prerequisites: ["add_to_20_no_bridge"],
    defaultState: "learning",
    order: 510,
  },
  {
    skillId: "series_sub",
    section: "series",
    title: "Убывающий ряд",
    shortTitle: "−шаг",
    description: "Продолжить ряд с вычитанием",
    prerequisites: ["sub_to_20_no_bridge"],
    defaultState: "learning",
    order: 520,
  },
  // Величины
  {
    skillId: "length_cm_dm",
    section: "length",
    title: "См → дм и см",
    shortTitle: "См→дм",
    description: "Перевести сантиметры в дециметры и сантиметры",
    prerequisites: [],
    defaultState: "learning",
    order: 610,
  },
  {
    skillId: "length_dm_cm",
    section: "length",
    title: "Дм и см → см",
    shortTitle: "Дм→см",
    description: "Перевести дециметры и сантиметры в сантиметры",
    prerequisites: [],
    defaultState: "learning",
    order: 620,
  },
  {
    skillId: "length_compare",
    section: "length",
    title: "Сравнить длины",
    shortTitle: "Сравнить",
    description: "Сравнить простые величины длины",
    prerequisites: ["length_dm_cm"],
    defaultState: "practice",
    order: 630,
  },
  // Геометрия
  {
    skillId: "segment_length",
    section: "geometry",
    title: "Длина отрезка",
    shortTitle: "Длина",
    description: "Найти длину второго отрезка",
    prerequisites: ["add_to_20_no_bridge"],
    defaultState: "learning",
    order: 710,
  },
  {
    skillId: "segment_longer",
    section: "geometry",
    title: "На N см длиннее",
    shortTitle: "Длиннее",
    description: "Отрезок длиннее на N см",
    prerequisites: ["segment_length"],
    defaultState: "practice",
    order: 720,
  },
  {
    skillId: "segment_shorter",
    section: "geometry",
    title: "На N см короче",
    shortTitle: "Короче",
    description: "Отрезок короче на N см",
    prerequisites: ["segment_length"],
    defaultState: "practice",
    order: 730,
  },
  // Умножение
  {
    skillId: "multiplication_concept",
    section: "multiplication",
    title: "Смысл умножения",
    shortTitle: "Смысл",
    description: "a × b = a групп по b",
    prerequisites: ["add_to_20_bridge"],
    defaultState: "learning",
    order: 810,
  },
  {
    skillId: "times_2",
    section: "multiplication",
    title: "Таблица ×2",
    shortTitle: "×2",
    description: "Умножение на 2",
    prerequisites: ["multiplication_concept"],
    defaultState: "learning",
    order: 820,
  },
  {
    skillId: "times_3",
    section: "multiplication",
    title: "Таблица ×3",
    shortTitle: "×3",
    description: "Умножение на 3",
    prerequisites: ["times_2"],
    defaultState: "learning",
    order: 830,
  },
  {
    skillId: "times_4",
    section: "multiplication",
    title: "Таблица ×4",
    shortTitle: "×4",
    description: "Умножение на 4",
    prerequisites: ["times_3"],
    defaultState: "learning",
    order: 840,
  },
  {
    skillId: "times_5",
    section: "multiplication",
    title: "Таблица ×5",
    shortTitle: "×5",
    description: "Умножение на 5",
    prerequisites: ["times_4"],
    defaultState: "learning",
    order: 850,
  },
  {
    skillId: "times_6",
    section: "multiplication",
    title: "Таблица ×6",
    shortTitle: "×6",
    description: "Умножение на 6",
    prerequisites: ["times_5"],
    defaultState: "learning",
    order: 860,
  },
  {
    skillId: "times_7",
    section: "multiplication",
    title: "Таблица ×7",
    shortTitle: "×7",
    description: "Умножение на 7",
    prerequisites: ["times_6"],
    defaultState: "learning",
    order: 870,
  },
  {
    skillId: "times_8",
    section: "multiplication",
    title: "Таблица ×8",
    shortTitle: "×8",
    description: "Умножение на 8",
    prerequisites: ["times_7"],
    defaultState: "learning",
    order: 880,
  },
  {
    skillId: "times_9",
    section: "multiplication",
    title: "Таблица ×9",
    shortTitle: "×9",
    description: "Умножение на 9",
    prerequisites: ["times_8"],
    defaultState: "learning",
    order: 890,
  },
  // Деление (в UI пока не показываем)
  {
    skillId: "division_concept",
    section: "division",
    title: "Смысл деления",
    shortTitle: "Смысл",
    description: "Деление как разбиение на равные группы",
    prerequisites: ["multiplication_concept"],
    defaultState: "locked",
    order: 910,
  },
  {
    skillId: "division_by_2",
    section: "division",
    title: "Деление на 2",
    shortTitle: "÷2",
    description: "Деление на 2",
    prerequisites: ["division_concept", "times_2"],
    defaultState: "locked",
    order: 920,
  },
  {
    skillId: "division_by_3",
    section: "division",
    title: "Деление на 3",
    shortTitle: "÷3",
    description: "Деление на 3",
    prerequisites: ["division_by_2", "times_3"],
    defaultState: "locked",
    order: 930,
  },
  {
    skillId: "division_by_4",
    section: "division",
    title: "Деление на 4",
    shortTitle: "÷4",
    description: "Деление на 4",
    prerequisites: ["division_by_3", "times_4"],
    defaultState: "locked",
    order: 940,
  },
  {
    skillId: "division_by_5",
    section: "division",
    title: "Деление на 5",
    shortTitle: "÷5",
    description: "Деление на 5",
    prerequisites: ["division_by_4", "times_5"],
    defaultState: "locked",
    order: 950,
  },
  {
    skillId: "division_by_6",
    section: "division",
    title: "Деление на 6",
    shortTitle: "÷6",
    description: "Деление на 6",
    prerequisites: ["division_by_5", "times_6"],
    defaultState: "locked",
    order: 960,
  },
  {
    skillId: "division_by_7",
    section: "division",
    title: "Деление на 7",
    shortTitle: "÷7",
    description: "Деление на 7",
    prerequisites: ["division_by_6", "times_7"],
    defaultState: "locked",
    order: 970,
  },
  {
    skillId: "division_by_8",
    section: "division",
    title: "Деление на 8",
    shortTitle: "÷8",
    description: "Деление на 8",
    prerequisites: ["division_by_7", "times_8"],
    defaultState: "locked",
    order: 980,
  },
  {
    skillId: "division_by_9",
    section: "division",
    title: "Деление на 9",
    shortTitle: "÷9",
    description: "Деление на 9",
    prerequisites: ["division_by_8", "times_9"],
    defaultState: "locked",
    order: 990,
  },
];

export const MATH_CURRICULUM_BY_ID: Record<MathSkillId, CurriculumSkill> = Object.fromEntries(
  MATH_CURRICULUM.map((s) => [s.skillId, s]),
) as Record<MathSkillId, CurriculumSkill>;

export const SECTION_TITLES: Record<MathSection, string> = {
  addition: "Сложение",
  subtraction: "Вычитание",
  compare: "Сравнение",
  missing: "Найди число",
  word: "Задачи",
  series: "Ряды",
  length: "Величины",
  geometry: "Геометрия",
  multiplication: "Умножение",
  division: "Деление",
};

/** Базовые навыки, доступные в Today по умолчанию (без умножения). */
export const DEFAULT_TODAY_SKILLS: MathSkillId[] = [
  "add_to_10",
  "add_to_20_no_bridge",
  "add_to_20_bridge",
  "sub_to_10",
  "sub_to_20_no_bridge",
  "sub_to_20_bridge",
  "compare_numbers",
  "compare_expression_number",
  "missing_addend",
  "missing_minuend",
  "missing_subtrahend",
  "word_add",
  "word_sub",
  "word_two_step",
  "series_add",
  "series_sub",
];

export function skillsBySection(section: MathSection): CurriculumSkill[] {
  return MATH_CURRICULUM.filter((s) => s.section === section).sort((a, b) => a.order - b.order);
}

export function defaultSkillStates(): Record<MathSkillId, SkillState> {
  const out = {} as Record<MathSkillId, SkillState>;
  for (const skill of MATH_CURRICULUM) {
    out[skill.skillId] = skill.defaultState;
  }
  return out;
}
